using NUnit.Framework;
using MVCApp.Services;
using MVCApp.Models;
using System.Collections.Generic;

namespace Prototype.Tests.ServiceTests
{
    [TestFixture]
    public class TicketDataLoggerTests
    {
        [Test]
        public void LogChangeTest()
        {
            TicketDataLogger tdl = new TicketDataLogger();
            string action = "LogChangeTest", details = "Entry generated by automated unit test";
            int entryId = 5;

            Assert.IsTrue(tdl.LogChange(action, details, entryId));
        }
    }
}